export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_BIKES_SUCCESS = 'LOAD_BIKES_SUCCESS';
export const CREATE_BIKE_SUCCESS = 'CREATE_BIKE_SUCCESS';
export const UPDATE_BIKE_SUCCESS = 'UPDATE_BIKE_SUCCESS';
export const DELETE_BIKE_SUCCESS = 'DELETE_BIKE_SUCCESS';
export const BIKE_IMAGE_UPLOAD_SUCCESS = 'BIKE_IMAGE_UPLOAD_SUCCESS';
export const BIKE_IMAGE_URL_LOAD_SUCCESS = 'BIKE_IMAGE_URL_LOAD_SUCCESS';
export const CURRENT_BIKE_SAVE = 'CURRENT_BIKE_SAVE';
export const CURRENT_BIKE_FILTER_SAVE='CURRENT_BIKE_FILTER_SAVE';
export const RATE_RESERVATION_SUCCESS='RATE_RESERVATION_SUCCESS';

export const LOAD_COLORS_SUCCESS = 'LOAD_COLORS_SUCCESS';
export const CREATE_COLOR_SUCCESS = 'CREATE_COLOR_SUCCESS';
export const DELETE_COLOR_SUCCESS = 'DELETE_COLOR_SUCCESS';

export const BIKE_RESERVE_SUCCESS = 'BIKE_RESERVE_SUCCESS';
export const CANCEL_RESERVE_SUCCESS = 'CANCEL_RESERVE_SUCCESS';

export const AUTHENTICATE_START    = 'AUTHENTICATE_START';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_ERROR    = 'AUTHENTICATE_ERROR';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const LOAD_USER_DATA_SUCCESS = 'LOAD_USER_DATA_SUCCESS';
export const LOAD_ALL_USERS_DATA_SUCCESS = 'LOAD_ALL_USERS_DATA_SUCCESS';
export const LOAD_ALL_USERS_SUCCESS = 'LOAD_ALL_USERS_SUCCESS';
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS';

export const GET_NEW_KEY_SUCCESS = 'GET_NEW_KEY_SUCCESS';
export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS';
